import type { IMedicine } from '@/models/Medicine';

type MedicineCategory = IMedicine['category'];

export interface GhanaMedicineSeed {
  name: string;
  genericName: string;
  category: MedicineCategory;
  dosageForm: string;
  strength: string;
  unit: string;
  prescriptionRequired: boolean;
  unitCost: number;
  sellingPrice: number;
  currentStock: number;
  reorderLevel: number;
  maxStock: number;
  shelfLocation: string;
  description: string;
  storageConditions?: string;
}

const oral = 'Store below 30C in a dry place';
const cold = 'Store in cold chain according to product label';
const topical = 'Store below 30C and keep container closed';

export const ghanaMedicineCatalog: GhanaMedicineSeed[] = [
  { name: 'Paracetamol 500mg Tablet', genericName: 'Paracetamol', category: 'tablet', dosageForm: 'Tablet', strength: '500mg', unit: 'tablets', prescriptionRequired: false, unitCost: 0.08, sellingPrice: 0.2, currentStock: 3000, reorderLevel: 500, maxStock: 6000, shelfLocation: 'A1-01', description: 'Analgesic and antipyretic', storageConditions: oral },
  { name: 'Paracetamol 120mg/5ml Syrup', genericName: 'Paracetamol', category: 'syrup', dosageForm: 'Syrup', strength: '120mg/5ml', unit: 'bottles', prescriptionRequired: false, unitCost: 7, sellingPrice: 12, currentStock: 160, reorderLevel: 30, maxStock: 300, shelfLocation: 'A1-02', description: 'Pediatric analgesic and antipyretic', storageConditions: oral },
  { name: 'Ibuprofen 400mg Tablet', genericName: 'Ibuprofen', category: 'tablet', dosageForm: 'Tablet', strength: '400mg', unit: 'tablets', prescriptionRequired: false, unitCost: 0.12, sellingPrice: 0.35, currentStock: 1200, reorderLevel: 250, maxStock: 3000, shelfLocation: 'A1-03', description: 'Non-steroidal anti-inflammatory medicine', storageConditions: oral },
  { name: 'Diclofenac 50mg Tablet', genericName: 'Diclofenac sodium', category: 'tablet', dosageForm: 'Tablet', strength: '50mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.1, sellingPrice: 0.3, currentStock: 900, reorderLevel: 200, maxStock: 2500, shelfLocation: 'A1-04', description: 'NSAID analgesic', storageConditions: oral },
  { name: 'Diclofenac 75mg/3ml Injection', genericName: 'Diclofenac sodium', category: 'injection', dosageForm: 'Injection', strength: '75mg/3ml', unit: 'ampoules', prescriptionRequired: true, unitCost: 2.2, sellingPrice: 5, currentStock: 120, reorderLevel: 30, maxStock: 300, shelfLocation: 'A1-05', description: 'Injectable NSAID analgesic', storageConditions: oral },
  { name: 'Tramadol 50mg Capsule', genericName: 'Tramadol', category: 'capsule', dosageForm: 'Capsule', strength: '50mg', unit: 'capsules', prescriptionRequired: true, unitCost: 0.35, sellingPrice: 0.9, currentStock: 400, reorderLevel: 100, maxStock: 1000, shelfLocation: 'A1-06', description: 'Opioid analgesic for moderate to severe pain', storageConditions: oral },
  { name: 'Morphine 10mg/ml Injection', genericName: 'Morphine sulfate', category: 'injection', dosageForm: 'Injection', strength: '10mg/ml', unit: 'ampoules', prescriptionRequired: true, unitCost: 6, sellingPrice: 12, currentStock: 40, reorderLevel: 10, maxStock: 120, shelfLocation: 'A1-07', description: 'Strong opioid analgesic', storageConditions: oral },
  { name: 'Lignocaine 2% Injection', genericName: 'Lidocaine', category: 'injection', dosageForm: 'Injection', strength: '2%', unit: 'vials', prescriptionRequired: true, unitCost: 3.5, sellingPrice: 8, currentStock: 70, reorderLevel: 20, maxStock: 200, shelfLocation: 'A1-08', description: 'Local anesthetic', storageConditions: oral },

  { name: 'Amoxicillin 500mg Capsule', genericName: 'Amoxicillin', category: 'capsule', dosageForm: 'Capsule', strength: '500mg', unit: 'capsules', prescriptionRequired: true, unitCost: 0.35, sellingPrice: 0.8, currentStock: 1500, reorderLevel: 300, maxStock: 4000, shelfLocation: 'B1-01', description: 'Beta-lactam antibiotic', storageConditions: oral },
  { name: 'Amoxicillin 125mg/5ml Suspension', genericName: 'Amoxicillin', category: 'suspension', dosageForm: 'Suspension', strength: '125mg/5ml', unit: 'bottles', prescriptionRequired: true, unitCost: 13, sellingPrice: 24, currentStock: 150, reorderLevel: 40, maxStock: 350, shelfLocation: 'B1-02', description: 'Pediatric beta-lactam antibiotic', storageConditions: oral },
  { name: 'Amoxicillin/Clavulanic Acid 625mg Tablet', genericName: 'Amoxicillin + Clavulanic acid', category: 'tablet', dosageForm: 'Tablet', strength: '500mg/125mg', unit: 'tablets', prescriptionRequired: true, unitCost: 2.1, sellingPrice: 4, currentStock: 500, reorderLevel: 100, maxStock: 1200, shelfLocation: 'B1-03', description: 'Broad spectrum beta-lactam antibiotic', storageConditions: oral },
  { name: 'Ampicillin 500mg Injection', genericName: 'Ampicillin', category: 'injection', dosageForm: 'Injection', strength: '500mg', unit: 'vials', prescriptionRequired: true, unitCost: 3.2, sellingPrice: 7, currentStock: 150, reorderLevel: 30, maxStock: 400, shelfLocation: 'B1-04', description: 'Injectable penicillin antibiotic', storageConditions: oral },
  { name: 'Benzylpenicillin 1MU Injection', genericName: 'Benzylpenicillin', category: 'injection', dosageForm: 'Injection', strength: '1 million IU', unit: 'vials', prescriptionRequired: true, unitCost: 2.4, sellingPrice: 5, currentStock: 120, reorderLevel: 30, maxStock: 400, shelfLocation: 'B1-05', description: 'Injectable penicillin antibiotic', storageConditions: oral },
  { name: 'Phenoxymethylpenicillin 250mg Tablet', genericName: 'Phenoxymethylpenicillin', category: 'tablet', dosageForm: 'Tablet', strength: '250mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.2, sellingPrice: 0.45, currentStock: 500, reorderLevel: 100, maxStock: 1500, shelfLocation: 'B1-06', description: 'Oral penicillin antibiotic', storageConditions: oral },
  { name: 'Cloxacillin 500mg Capsule', genericName: 'Cloxacillin', category: 'capsule', dosageForm: 'Capsule', strength: '500mg', unit: 'capsules', prescriptionRequired: true, unitCost: 0.45, sellingPrice: 1, currentStock: 700, reorderLevel: 150, maxStock: 2000, shelfLocation: 'B1-07', description: 'Anti-staphylococcal penicillin', storageConditions: oral },
  { name: 'Ceftriaxone 1g Injection', genericName: 'Ceftriaxone', category: 'injection', dosageForm: 'Injection', strength: '1g', unit: 'vials', prescriptionRequired: true, unitCost: 6.5, sellingPrice: 12, currentStock: 250, reorderLevel: 60, maxStock: 700, shelfLocation: 'B1-08', description: 'Third-generation cephalosporin antibiotic', storageConditions: oral },
  { name: 'Cefuroxime 500mg Tablet', genericName: 'Cefuroxime', category: 'tablet', dosageForm: 'Tablet', strength: '500mg', unit: 'tablets', prescriptionRequired: true, unitCost: 1.1, sellingPrice: 2.5, currentStock: 450, reorderLevel: 100, maxStock: 1200, shelfLocation: 'B1-09', description: 'Second-generation cephalosporin antibiotic', storageConditions: oral },
  { name: 'Ciprofloxacin 500mg Tablet', genericName: 'Ciprofloxacin', category: 'tablet', dosageForm: 'Tablet', strength: '500mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.4, sellingPrice: 1, currentStock: 900, reorderLevel: 180, maxStock: 2400, shelfLocation: 'B2-01', description: 'Fluoroquinolone antibiotic', storageConditions: oral },
  { name: 'Metronidazole 400mg Tablet', genericName: 'Metronidazole', category: 'tablet', dosageForm: 'Tablet', strength: '400mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.18, sellingPrice: 0.45, currentStock: 1200, reorderLevel: 250, maxStock: 3000, shelfLocation: 'B2-02', description: 'Antibacterial and antiprotozoal medicine', storageConditions: oral },
  { name: 'Metronidazole 5mg/ml Injection', genericName: 'Metronidazole', category: 'injection', dosageForm: 'Infusion', strength: '500mg/100ml', unit: 'bottles', prescriptionRequired: true, unitCost: 5, sellingPrice: 10, currentStock: 130, reorderLevel: 30, maxStock: 350, shelfLocation: 'B2-03', description: 'Injectable antibacterial and antiprotozoal medicine', storageConditions: oral },
  { name: 'Azithromycin 500mg Tablet', genericName: 'Azithromycin', category: 'tablet', dosageForm: 'Tablet', strength: '500mg', unit: 'tablets', prescriptionRequired: true, unitCost: 1.8, sellingPrice: 3.5, currentStock: 300, reorderLevel: 80, maxStock: 900, shelfLocation: 'B2-04', description: 'Macrolide antibiotic', storageConditions: oral },
  { name: 'Erythromycin 500mg Tablet', genericName: 'Erythromycin', category: 'tablet', dosageForm: 'Tablet', strength: '500mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.65, sellingPrice: 1.4, currentStock: 380, reorderLevel: 80, maxStock: 1000, shelfLocation: 'B2-05', description: 'Macrolide antibiotic', storageConditions: oral },
  { name: 'Doxycycline 100mg Capsule', genericName: 'Doxycycline', category: 'capsule', dosageForm: 'Capsule', strength: '100mg', unit: 'capsules', prescriptionRequired: true, unitCost: 0.3, sellingPrice: 0.75, currentStock: 700, reorderLevel: 160, maxStock: 1800, shelfLocation: 'B2-06', description: 'Tetracycline antibiotic', storageConditions: oral },
  { name: 'Gentamicin 80mg/2ml Injection', genericName: 'Gentamicin', category: 'injection', dosageForm: 'Injection', strength: '80mg/2ml', unit: 'ampoules', prescriptionRequired: true, unitCost: 1.8, sellingPrice: 4, currentStock: 170, reorderLevel: 40, maxStock: 450, shelfLocation: 'B2-07', description: 'Aminoglycoside antibiotic', storageConditions: oral },
  { name: 'Co-trimoxazole 480mg Tablet', genericName: 'Sulfamethoxazole + Trimethoprim', category: 'tablet', dosageForm: 'Tablet', strength: '400mg/80mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.16, sellingPrice: 0.4, currentStock: 900, reorderLevel: 200, maxStock: 2400, shelfLocation: 'B2-08', description: 'Antibacterial combination medicine', storageConditions: oral },
  { name: 'Nitrofurantoin 100mg Capsule', genericName: 'Nitrofurantoin', category: 'capsule', dosageForm: 'Capsule', strength: '100mg', unit: 'capsules', prescriptionRequired: true, unitCost: 0.55, sellingPrice: 1.2, currentStock: 350, reorderLevel: 80, maxStock: 900, shelfLocation: 'B2-09', description: 'Urinary tract antibacterial medicine', storageConditions: oral },
  { name: 'Fluconazole 150mg Capsule', genericName: 'Fluconazole', category: 'capsule', dosageForm: 'Capsule', strength: '150mg', unit: 'capsules', prescriptionRequired: true, unitCost: 1.5, sellingPrice: 3, currentStock: 250, reorderLevel: 60, maxStock: 700, shelfLocation: 'B3-01', description: 'Antifungal medicine', storageConditions: oral },
  { name: 'Griseofulvin 500mg Tablet', genericName: 'Griseofulvin', category: 'tablet', dosageForm: 'Tablet', strength: '500mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.9, sellingPrice: 1.8, currentStock: 180, reorderLevel: 50, maxStock: 500, shelfLocation: 'B3-02', description: 'Antifungal medicine', storageConditions: oral },
  { name: 'Clotrimazole 1% Cream', genericName: 'Clotrimazole', category: 'cream', dosageForm: 'Cream', strength: '1%', unit: 'tubes', prescriptionRequired: false, unitCost: 5, sellingPrice: 10, currentStock: 140, reorderLevel: 35, maxStock: 350, shelfLocation: 'B3-03', description: 'Topical antifungal medicine', storageConditions: topical },
  { name: 'Nystatin Oral Suspension', genericName: 'Nystatin', category: 'suspension', dosageForm: 'Oral suspension', strength: '100,000IU/ml', unit: 'bottles', prescriptionRequired: true, unitCost: 12, sellingPrice: 22, currentStock: 70, reorderLevel: 20, maxStock: 200, shelfLocation: 'B3-04', description: 'Antifungal oral suspension', storageConditions: oral },

  { name: 'Artemether/Lumefantrine 20/120mg Tablet', genericName: 'Artemether + Lumefantrine', category: 'tablet', dosageForm: 'Tablet', strength: '20mg/120mg', unit: 'packs', prescriptionRequired: true, unitCost: 8, sellingPrice: 15, currentStock: 300, reorderLevel: 80, maxStock: 800, shelfLocation: 'C1-01', description: 'Artemisinin-based combination therapy for malaria', storageConditions: oral },
  { name: 'Artesunate 60mg Injection', genericName: 'Artesunate', category: 'injection', dosageForm: 'Injection', strength: '60mg', unit: 'vials', prescriptionRequired: true, unitCost: 11, sellingPrice: 20, currentStock: 120, reorderLevel: 30, maxStock: 300, shelfLocation: 'C1-02', description: 'Injectable antimalarial medicine', storageConditions: oral },
  { name: 'Quinine 300mg Tablet', genericName: 'Quinine sulfate', category: 'tablet', dosageForm: 'Tablet', strength: '300mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.45, sellingPrice: 1, currentStock: 260, reorderLevel: 60, maxStock: 800, shelfLocation: 'C1-03', description: 'Antimalarial medicine', storageConditions: oral },
  { name: 'Primaquine 7.5mg Tablet', genericName: 'Primaquine', category: 'tablet', dosageForm: 'Tablet', strength: '7.5mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.35, sellingPrice: 0.8, currentStock: 160, reorderLevel: 40, maxStock: 500, shelfLocation: 'C1-04', description: 'Antimalarial medicine used for radical cure where indicated', storageConditions: oral },
  { name: 'Albendazole 400mg Tablet', genericName: 'Albendazole', category: 'tablet', dosageForm: 'Tablet', strength: '400mg', unit: 'tablets', prescriptionRequired: false, unitCost: 0.5, sellingPrice: 1.2, currentStock: 500, reorderLevel: 100, maxStock: 1400, shelfLocation: 'C2-01', description: 'Anthelmintic medicine', storageConditions: oral },
  { name: 'Mebendazole 100mg Tablet', genericName: 'Mebendazole', category: 'tablet', dosageForm: 'Tablet', strength: '100mg', unit: 'tablets', prescriptionRequired: false, unitCost: 0.18, sellingPrice: 0.45, currentStock: 500, reorderLevel: 100, maxStock: 1400, shelfLocation: 'C2-02', description: 'Anthelmintic medicine', storageConditions: oral },
  { name: 'Praziquantel 600mg Tablet', genericName: 'Praziquantel', category: 'tablet', dosageForm: 'Tablet', strength: '600mg', unit: 'tablets', prescriptionRequired: true, unitCost: 1.6, sellingPrice: 3, currentStock: 150, reorderLevel: 40, maxStock: 450, shelfLocation: 'C2-03', description: 'Anthelmintic medicine for schistosomiasis and cestodes', storageConditions: oral },

  { name: 'Amlodipine 5mg Tablet', genericName: 'Amlodipine', category: 'tablet', dosageForm: 'Tablet', strength: '5mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.12, sellingPrice: 0.35, currentStock: 1200, reorderLevel: 250, maxStock: 3000, shelfLocation: 'D1-01', description: 'Calcium channel blocker antihypertensive', storageConditions: oral },
  { name: 'Amlodipine 10mg Tablet', genericName: 'Amlodipine', category: 'tablet', dosageForm: 'Tablet', strength: '10mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.18, sellingPrice: 0.45, currentStock: 1000, reorderLevel: 200, maxStock: 2500, shelfLocation: 'D1-02', description: 'Calcium channel blocker antihypertensive', storageConditions: oral },
  { name: 'Nifedipine 20mg SR Tablet', genericName: 'Nifedipine', category: 'tablet', dosageForm: 'Sustained release tablet', strength: '20mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.25, sellingPrice: 0.6, currentStock: 450, reorderLevel: 100, maxStock: 1200, shelfLocation: 'D1-03', description: 'Calcium channel blocker antihypertensive', storageConditions: oral },
  { name: 'Lisinopril 10mg Tablet', genericName: 'Lisinopril', category: 'tablet', dosageForm: 'Tablet', strength: '10mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.2, sellingPrice: 0.5, currentStock: 800, reorderLevel: 180, maxStock: 2200, shelfLocation: 'D1-04', description: 'ACE inhibitor antihypertensive', storageConditions: oral },
  { name: 'Enalapril 5mg Tablet', genericName: 'Enalapril', category: 'tablet', dosageForm: 'Tablet', strength: '5mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.12, sellingPrice: 0.3, currentStock: 700, reorderLevel: 160, maxStock: 1800, shelfLocation: 'D1-05', description: 'ACE inhibitor antihypertensive', storageConditions: oral },
  { name: 'Losartan 50mg Tablet', genericName: 'Losartan', category: 'tablet', dosageForm: 'Tablet', strength: '50mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.35, sellingPrice: 0.8, currentStock: 700, reorderLevel: 150, maxStock: 1800, shelfLocation: 'D1-06', description: 'Angiotensin receptor blocker antihypertensive', storageConditions: oral },
  { name: 'Hydrochlorothiazide 25mg Tablet', genericName: 'Hydrochlorothiazide', category: 'tablet', dosageForm: 'Tablet', strength: '25mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.08, sellingPrice: 0.2, currentStock: 1000, reorderLevel: 220, maxStock: 2500, shelfLocation: 'D1-07', description: 'Thiazide diuretic', storageConditions: oral },
  { name: 'Furosemide 40mg Tablet', genericName: 'Furosemide', category: 'tablet', dosageForm: 'Tablet', strength: '40mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.09, sellingPrice: 0.25, currentStock: 900, reorderLevel: 200, maxStock: 2400, shelfLocation: 'D1-08', description: 'Loop diuretic', storageConditions: oral },
  { name: 'Furosemide 20mg/2ml Injection', genericName: 'Furosemide', category: 'injection', dosageForm: 'Injection', strength: '20mg/2ml', unit: 'ampoules', prescriptionRequired: true, unitCost: 1.2, sellingPrice: 3, currentStock: 120, reorderLevel: 30, maxStock: 350, shelfLocation: 'D1-09', description: 'Injectable loop diuretic', storageConditions: oral },
  { name: 'Atenolol 50mg Tablet', genericName: 'Atenolol', category: 'tablet', dosageForm: 'Tablet', strength: '50mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.14, sellingPrice: 0.35, currentStock: 550, reorderLevel: 120, maxStock: 1500, shelfLocation: 'D2-01', description: 'Beta blocker', storageConditions: oral },
  { name: 'Bisoprolol 5mg Tablet', genericName: 'Bisoprolol', category: 'tablet', dosageForm: 'Tablet', strength: '5mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.28, sellingPrice: 0.7, currentStock: 420, reorderLevel: 100, maxStock: 1200, shelfLocation: 'D2-02', description: 'Beta blocker', storageConditions: oral },
  { name: 'Methyldopa 250mg Tablet', genericName: 'Methyldopa', category: 'tablet', dosageForm: 'Tablet', strength: '250mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.3, sellingPrice: 0.75, currentStock: 400, reorderLevel: 100, maxStock: 1200, shelfLocation: 'D2-03', description: 'Centrally acting antihypertensive', storageConditions: oral },
  { name: 'Aspirin 75mg Tablet', genericName: 'Acetylsalicylic acid', category: 'tablet', dosageForm: 'Tablet', strength: '75mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.04, sellingPrice: 0.15, currentStock: 1500, reorderLevel: 300, maxStock: 4000, shelfLocation: 'D2-04', description: 'Antiplatelet medicine', storageConditions: oral },
  { name: 'Atorvastatin 20mg Tablet', genericName: 'Atorvastatin', category: 'tablet', dosageForm: 'Tablet', strength: '20mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.45, sellingPrice: 1, currentStock: 700, reorderLevel: 150, maxStock: 1800, shelfLocation: 'D2-05', description: 'Lipid lowering medicine', storageConditions: oral },
  { name: 'Simvastatin 20mg Tablet', genericName: 'Simvastatin', category: 'tablet', dosageForm: 'Tablet', strength: '20mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.22, sellingPrice: 0.55, currentStock: 500, reorderLevel: 120, maxStock: 1400, shelfLocation: 'D2-06', description: 'Lipid lowering medicine', storageConditions: oral },
  { name: 'Warfarin 5mg Tablet', genericName: 'Warfarin', category: 'tablet', dosageForm: 'Tablet', strength: '5mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.18, sellingPrice: 0.5, currentStock: 250, reorderLevel: 70, maxStock: 700, shelfLocation: 'D2-07', description: 'Oral anticoagulant', storageConditions: oral },
  { name: 'Heparin 5000IU/ml Injection', genericName: 'Heparin sodium', category: 'injection', dosageForm: 'Injection', strength: '5000IU/ml', unit: 'vials', prescriptionRequired: true, unitCost: 9, sellingPrice: 18, currentStock: 60, reorderLevel: 20, maxStock: 180, shelfLocation: 'D2-08', description: 'Injectable anticoagulant', storageConditions: oral },

  { name: 'Metformin 500mg Tablet', genericName: 'Metformin', category: 'tablet', dosageForm: 'Tablet', strength: '500mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.08, sellingPrice: 0.25, currentStock: 1500, reorderLevel: 300, maxStock: 4000, shelfLocation: 'E1-01', description: 'Biguanide antidiabetic medicine', storageConditions: oral },
  { name: 'Metformin 850mg Tablet', genericName: 'Metformin', category: 'tablet', dosageForm: 'Tablet', strength: '850mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.12, sellingPrice: 0.35, currentStock: 900, reorderLevel: 200, maxStock: 2500, shelfLocation: 'E1-02', description: 'Biguanide antidiabetic medicine', storageConditions: oral },
  { name: 'Glibenclamide 5mg Tablet', genericName: 'Glibenclamide', category: 'tablet', dosageForm: 'Tablet', strength: '5mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.06, sellingPrice: 0.2, currentStock: 900, reorderLevel: 180, maxStock: 2200, shelfLocation: 'E1-03', description: 'Sulfonylurea antidiabetic medicine', storageConditions: oral },
  { name: 'Gliclazide 80mg Tablet', genericName: 'Gliclazide', category: 'tablet', dosageForm: 'Tablet', strength: '80mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.18, sellingPrice: 0.45, currentStock: 650, reorderLevel: 140, maxStock: 1800, shelfLocation: 'E1-04', description: 'Sulfonylurea antidiabetic medicine', storageConditions: oral },
  { name: 'Insulin Regular 100IU/ml Injection', genericName: 'Soluble insulin', category: 'injection', dosageForm: 'Injection', strength: '100IU/ml', unit: 'vials', prescriptionRequired: true, unitCost: 34, sellingPrice: 50, currentStock: 50, reorderLevel: 15, maxStock: 150, shelfLocation: 'Cold-01', description: 'Short acting insulin', storageConditions: cold },
  { name: 'Insulin NPH 100IU/ml Injection', genericName: 'Isophane insulin', category: 'injection', dosageForm: 'Injection', strength: '100IU/ml', unit: 'vials', prescriptionRequired: true, unitCost: 34, sellingPrice: 50, currentStock: 50, reorderLevel: 15, maxStock: 150, shelfLocation: 'Cold-02', description: 'Intermediate acting insulin', storageConditions: cold },

  { name: 'Salbutamol 100microgram Inhaler', genericName: 'Salbutamol', category: 'inhaler', dosageForm: 'Inhaler', strength: '100microgram/dose', unit: 'inhalers', prescriptionRequired: true, unitCost: 20, sellingPrice: 35, currentStock: 80, reorderLevel: 20, maxStock: 220, shelfLocation: 'F1-01', description: 'Short acting beta agonist bronchodilator', storageConditions: oral },
  { name: 'Salbutamol 2mg/5ml Syrup', genericName: 'Salbutamol', category: 'syrup', dosageForm: 'Syrup', strength: '2mg/5ml', unit: 'bottles', prescriptionRequired: true, unitCost: 6, sellingPrice: 12, currentStock: 100, reorderLevel: 25, maxStock: 250, shelfLocation: 'F1-02', description: 'Bronchodilator syrup', storageConditions: oral },
  { name: 'Beclometasone 100microgram Inhaler', genericName: 'Beclometasone', category: 'inhaler', dosageForm: 'Inhaler', strength: '100microgram/dose', unit: 'inhalers', prescriptionRequired: true, unitCost: 28, sellingPrice: 48, currentStock: 60, reorderLevel: 15, maxStock: 180, shelfLocation: 'F1-03', description: 'Inhaled corticosteroid', storageConditions: oral },
  { name: 'Prednisolone 5mg Tablet', genericName: 'Prednisolone', category: 'tablet', dosageForm: 'Tablet', strength: '5mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.08, sellingPrice: 0.25, currentStock: 1000, reorderLevel: 200, maxStock: 2400, shelfLocation: 'F1-04', description: 'Corticosteroid medicine', storageConditions: oral },
  { name: 'Hydrocortisone 100mg Injection', genericName: 'Hydrocortisone', category: 'injection', dosageForm: 'Injection', strength: '100mg', unit: 'vials', prescriptionRequired: true, unitCost: 5, sellingPrice: 10, currentStock: 100, reorderLevel: 25, maxStock: 250, shelfLocation: 'F1-05', description: 'Injectable corticosteroid', storageConditions: oral },

  { name: 'Omeprazole 20mg Capsule', genericName: 'Omeprazole', category: 'capsule', dosageForm: 'Capsule', strength: '20mg', unit: 'capsules', prescriptionRequired: true, unitCost: 0.18, sellingPrice: 0.45, currentStock: 1200, reorderLevel: 250, maxStock: 3000, shelfLocation: 'G1-01', description: 'Proton pump inhibitor', storageConditions: oral },
  { name: 'Pantoprazole 40mg Tablet', genericName: 'Pantoprazole', category: 'tablet', dosageForm: 'Tablet', strength: '40mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.5, sellingPrice: 1.1, currentStock: 700, reorderLevel: 150, maxStock: 1800, shelfLocation: 'G1-02', description: 'Proton pump inhibitor', storageConditions: oral },
  { name: 'Ranitidine 150mg Tablet', genericName: 'Ranitidine', category: 'tablet', dosageForm: 'Tablet', strength: '150mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.15, sellingPrice: 0.4, currentStock: 300, reorderLevel: 80, maxStock: 900, shelfLocation: 'G1-03', description: 'H2 receptor antagonist where locally supplied', storageConditions: oral },
  { name: 'Oral Rehydration Salts Sachet', genericName: 'Oral rehydration salts', category: 'powder', dosageForm: 'Powder for solution', strength: 'Low osmolarity sachet', unit: 'sachets', prescriptionRequired: false, unitCost: 0.6, sellingPrice: 1.2, currentStock: 1000, reorderLevel: 250, maxStock: 3000, shelfLocation: 'G1-04', description: 'Oral rehydration therapy', storageConditions: oral },
  { name: 'Zinc Sulfate 20mg Tablet', genericName: 'Zinc sulfate', category: 'tablet', dosageForm: 'Dispersible tablet', strength: '20mg', unit: 'tablets', prescriptionRequired: false, unitCost: 0.08, sellingPrice: 0.2, currentStock: 800, reorderLevel: 180, maxStock: 2200, shelfLocation: 'G1-05', description: 'Zinc supplementation for diarrhea management', storageConditions: oral },
  { name: 'Loperamide 2mg Capsule', genericName: 'Loperamide', category: 'capsule', dosageForm: 'Capsule', strength: '2mg', unit: 'capsules', prescriptionRequired: false, unitCost: 0.18, sellingPrice: 0.45, currentStock: 400, reorderLevel: 100, maxStock: 1200, shelfLocation: 'G1-06', description: 'Antidiarrheal medicine', storageConditions: oral },
  { name: 'Bisacodyl 5mg Tablet', genericName: 'Bisacodyl', category: 'tablet', dosageForm: 'Tablet', strength: '5mg', unit: 'tablets', prescriptionRequired: false, unitCost: 0.1, sellingPrice: 0.3, currentStock: 350, reorderLevel: 80, maxStock: 1000, shelfLocation: 'G1-07', description: 'Stimulant laxative', storageConditions: oral },
  { name: 'Hyoscine Butylbromide 10mg Tablet', genericName: 'Hyoscine butylbromide', category: 'tablet', dosageForm: 'Tablet', strength: '10mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.25, sellingPrice: 0.6, currentStock: 500, reorderLevel: 120, maxStock: 1400, shelfLocation: 'G1-08', description: 'Antispasmodic medicine', storageConditions: oral },
  { name: 'Metoclopramide 10mg Tablet', genericName: 'Metoclopramide', category: 'tablet', dosageForm: 'Tablet', strength: '10mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.08, sellingPrice: 0.25, currentStock: 600, reorderLevel: 140, maxStock: 1600, shelfLocation: 'G2-01', description: 'Antiemetic medicine', storageConditions: oral },
  { name: 'Ondansetron 4mg Tablet', genericName: 'Ondansetron', category: 'tablet', dosageForm: 'Tablet', strength: '4mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.8, sellingPrice: 1.8, currentStock: 220, reorderLevel: 60, maxStock: 600, shelfLocation: 'G2-02', description: 'Antiemetic medicine', storageConditions: oral },

  { name: 'Ferrous Sulfate 200mg Tablet', genericName: 'Ferrous sulfate', category: 'tablet', dosageForm: 'Tablet', strength: '200mg', unit: 'tablets', prescriptionRequired: false, unitCost: 0.06, sellingPrice: 0.18, currentStock: 1200, reorderLevel: 260, maxStock: 3000, shelfLocation: 'H1-01', description: 'Iron supplement', storageConditions: oral },
  { name: 'Folic Acid 5mg Tablet', genericName: 'Folic acid', category: 'tablet', dosageForm: 'Tablet', strength: '5mg', unit: 'tablets', prescriptionRequired: false, unitCost: 0.04, sellingPrice: 0.15, currentStock: 1500, reorderLevel: 300, maxStock: 4000, shelfLocation: 'H1-02', description: 'Folate supplement', storageConditions: oral },
  { name: 'Vitamin B Complex Tablet', genericName: 'Vitamin B complex', category: 'tablet', dosageForm: 'Tablet', strength: 'Standard strength', unit: 'tablets', prescriptionRequired: false, unitCost: 0.08, sellingPrice: 0.25, currentStock: 1000, reorderLevel: 220, maxStock: 2500, shelfLocation: 'H1-03', description: 'Vitamin supplement', storageConditions: oral },
  { name: 'Vitamin C 500mg Tablet', genericName: 'Ascorbic acid', category: 'tablet', dosageForm: 'Tablet', strength: '500mg', unit: 'tablets', prescriptionRequired: false, unitCost: 0.08, sellingPrice: 0.25, currentStock: 1000, reorderLevel: 220, maxStock: 2500, shelfLocation: 'H1-04', description: 'Vitamin C supplement', storageConditions: oral },
  { name: 'Multivitamin Syrup', genericName: 'Multivitamins', category: 'syrup', dosageForm: 'Syrup', strength: 'Standard pediatric formulation', unit: 'bottles', prescriptionRequired: false, unitCost: 8, sellingPrice: 15, currentStock: 120, reorderLevel: 30, maxStock: 300, shelfLocation: 'H1-05', description: 'Multivitamin supplement', storageConditions: oral },
  { name: 'Calcium Carbonate 500mg Tablet', genericName: 'Calcium carbonate', category: 'tablet', dosageForm: 'Tablet', strength: '500mg', unit: 'tablets', prescriptionRequired: false, unitCost: 0.12, sellingPrice: 0.3, currentStock: 650, reorderLevel: 150, maxStock: 1800, shelfLocation: 'H1-06', description: 'Calcium supplement and antacid', storageConditions: oral },

  { name: 'Chlorpheniramine 4mg Tablet', genericName: 'Chlorpheniramine', category: 'tablet', dosageForm: 'Tablet', strength: '4mg', unit: 'tablets', prescriptionRequired: false, unitCost: 0.05, sellingPrice: 0.15, currentStock: 1200, reorderLevel: 260, maxStock: 3200, shelfLocation: 'I1-01', description: 'Antihistamine medicine', storageConditions: oral },
  { name: 'Cetirizine 10mg Tablet', genericName: 'Cetirizine', category: 'tablet', dosageForm: 'Tablet', strength: '10mg', unit: 'tablets', prescriptionRequired: false, unitCost: 0.12, sellingPrice: 0.35, currentStock: 1000, reorderLevel: 220, maxStock: 2600, shelfLocation: 'I1-02', description: 'Non-sedating antihistamine', storageConditions: oral },
  { name: 'Promethazine 25mg Tablet', genericName: 'Promethazine', category: 'tablet', dosageForm: 'Tablet', strength: '25mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.14, sellingPrice: 0.35, currentStock: 450, reorderLevel: 100, maxStock: 1200, shelfLocation: 'I1-03', description: 'Antihistamine and antiemetic medicine', storageConditions: oral },
  { name: 'Adrenaline 1mg/ml Injection', genericName: 'Adrenaline', category: 'injection', dosageForm: 'Injection', strength: '1mg/ml', unit: 'ampoules', prescriptionRequired: true, unitCost: 2.2, sellingPrice: 5, currentStock: 80, reorderLevel: 20, maxStock: 220, shelfLocation: 'I1-04', description: 'Emergency anaphylaxis and resuscitation medicine', storageConditions: oral },

  { name: 'Carbamazepine 200mg Tablet', genericName: 'Carbamazepine', category: 'tablet', dosageForm: 'Tablet', strength: '200mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.22, sellingPrice: 0.55, currentStock: 500, reorderLevel: 120, maxStock: 1400, shelfLocation: 'J1-01', description: 'Antiepileptic medicine', storageConditions: oral },
  { name: 'Sodium Valproate 200mg Tablet', genericName: 'Sodium valproate', category: 'tablet', dosageForm: 'Tablet', strength: '200mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.35, sellingPrice: 0.8, currentStock: 380, reorderLevel: 90, maxStock: 1000, shelfLocation: 'J1-02', description: 'Antiepileptic medicine', storageConditions: oral },
  { name: 'Diazepam 5mg Tablet', genericName: 'Diazepam', category: 'tablet', dosageForm: 'Tablet', strength: '5mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.08, sellingPrice: 0.25, currentStock: 250, reorderLevel: 70, maxStock: 700, shelfLocation: 'J1-03', description: 'Benzodiazepine medicine', storageConditions: oral },
  { name: 'Diazepam 10mg/2ml Injection', genericName: 'Diazepam', category: 'injection', dosageForm: 'Injection', strength: '10mg/2ml', unit: 'ampoules', prescriptionRequired: true, unitCost: 2.2, sellingPrice: 5, currentStock: 70, reorderLevel: 20, maxStock: 200, shelfLocation: 'J1-04', description: 'Injectable benzodiazepine medicine', storageConditions: oral },
  { name: 'Haloperidol 5mg Tablet', genericName: 'Haloperidol', category: 'tablet', dosageForm: 'Tablet', strength: '5mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.12, sellingPrice: 0.35, currentStock: 300, reorderLevel: 80, maxStock: 900, shelfLocation: 'J1-05', description: 'Antipsychotic medicine', storageConditions: oral },
  { name: 'Amitriptyline 25mg Tablet', genericName: 'Amitriptyline', category: 'tablet', dosageForm: 'Tablet', strength: '25mg', unit: 'tablets', prescriptionRequired: true, unitCost: 0.08, sellingPrice: 0.25, currentStock: 450, reorderLevel: 100, maxStock: 1200, shelfLocation: 'J1-06', description: 'Tricyclic antidepressant', storageConditions: oral },
  { name: 'Fluoxetine 20mg Capsule', genericName: 'Fluoxetine', category: 'capsule', dosageForm: 'Capsule', strength: '20mg', unit: 'capsules', prescriptionRequired: true, unitCost: 0.35, sellingPrice: 0.8, currentStock: 350, reorderLevel: 90, maxStock: 1000, shelfLocation: 'J1-07', description: 'Selective serotonin reuptake inhibitor', storageConditions: oral },

  { name: 'Oxytocin 10IU/ml Injection', genericName: 'Oxytocin', category: 'injection', dosageForm: 'Injection', strength: '10IU/ml', unit: 'ampoules', prescriptionRequired: true, unitCost: 2.5, sellingPrice: 5, currentStock: 100, reorderLevel: 25, maxStock: 250, shelfLocation: 'Cold-03', description: 'Uterotonic medicine', storageConditions: cold },
  { name: 'Misoprostol 200microgram Tablet', genericName: 'Misoprostol', category: 'tablet', dosageForm: 'Tablet', strength: '200microgram', unit: 'tablets', prescriptionRequired: true, unitCost: 0.7, sellingPrice: 1.5, currentStock: 220, reorderLevel: 60, maxStock: 600, shelfLocation: 'K1-01', description: 'Uterotonic medicine', storageConditions: oral },
  { name: 'Magnesium Sulfate 50% Injection', genericName: 'Magnesium sulfate', category: 'injection', dosageForm: 'Injection', strength: '50%', unit: 'ampoules', prescriptionRequired: true, unitCost: 3.8, sellingPrice: 8, currentStock: 80, reorderLevel: 20, maxStock: 220, shelfLocation: 'K1-02', description: 'Anticonvulsant for obstetric emergencies', storageConditions: oral },
  { name: 'Tranexamic Acid 500mg/5ml Injection', genericName: 'Tranexamic acid', category: 'injection', dosageForm: 'Injection', strength: '500mg/5ml', unit: 'ampoules', prescriptionRequired: true, unitCost: 5.5, sellingPrice: 11, currentStock: 80, reorderLevel: 20, maxStock: 220, shelfLocation: 'K1-03', description: 'Antifibrinolytic medicine', storageConditions: oral },
  { name: 'Levonorgestrel 1.5mg Tablet', genericName: 'Levonorgestrel', category: 'tablet', dosageForm: 'Tablet', strength: '1.5mg', unit: 'tablets', prescriptionRequired: true, unitCost: 5, sellingPrice: 10, currentStock: 120, reorderLevel: 30, maxStock: 350, shelfLocation: 'K1-04', description: 'Emergency contraceptive medicine', storageConditions: oral },
  { name: 'Combined Oral Contraceptive Tablet', genericName: 'Ethinylestradiol + Levonorgestrel', category: 'tablet', dosageForm: 'Tablet pack', strength: '30microgram/150microgram', unit: 'packs', prescriptionRequired: true, unitCost: 4, sellingPrice: 8, currentStock: 150, reorderLevel: 40, maxStock: 400, shelfLocation: 'K1-05', description: 'Combined hormonal contraceptive', storageConditions: oral },

  { name: 'Sodium Chloride 0.9% Infusion', genericName: 'Sodium chloride', category: 'solution', dosageForm: 'Infusion', strength: '0.9% 500ml', unit: 'bags', prescriptionRequired: true, unitCost: 5, sellingPrice: 9, currentStock: 220, reorderLevel: 60, maxStock: 600, shelfLocation: 'L1-01', description: 'Intravenous crystalloid fluid', storageConditions: oral },
  { name: 'Dextrose 5% Infusion', genericName: 'Dextrose', category: 'solution', dosageForm: 'Infusion', strength: '5% 500ml', unit: 'bags', prescriptionRequired: true, unitCost: 5, sellingPrice: 9, currentStock: 200, reorderLevel: 60, maxStock: 600, shelfLocation: 'L1-02', description: 'Intravenous glucose fluid', storageConditions: oral },
  { name: 'Ringers Lactate Infusion', genericName: 'Compound sodium lactate', category: 'solution', dosageForm: 'Infusion', strength: '500ml', unit: 'bags', prescriptionRequired: true, unitCost: 5.5, sellingPrice: 10, currentStock: 200, reorderLevel: 60, maxStock: 600, shelfLocation: 'L1-03', description: 'Intravenous crystalloid fluid', storageConditions: oral },
  { name: 'Potassium Chloride 15% Injection', genericName: 'Potassium chloride', category: 'injection', dosageForm: 'Injection', strength: '15%', unit: 'ampoules', prescriptionRequired: true, unitCost: 2.5, sellingPrice: 5, currentStock: 60, reorderLevel: 20, maxStock: 180, shelfLocation: 'L1-04', description: 'Electrolyte replacement concentrate', storageConditions: oral },
  { name: 'Water for Injection 10ml', genericName: 'Water for injection', category: 'injection', dosageForm: 'Injection solvent', strength: '10ml', unit: 'ampoules', prescriptionRequired: false, unitCost: 0.6, sellingPrice: 1.2, currentStock: 500, reorderLevel: 120, maxStock: 1200, shelfLocation: 'L1-05', description: 'Sterile solvent for injection preparation', storageConditions: oral },

  { name: 'Chloramphenicol Eye Drops 0.5%', genericName: 'Chloramphenicol', category: 'drops', dosageForm: 'Eye drops', strength: '0.5%', unit: 'bottles', prescriptionRequired: true, unitCost: 5, sellingPrice: 10, currentStock: 80, reorderLevel: 20, maxStock: 220, shelfLocation: 'M1-01', description: 'Antibacterial eye drops', storageConditions: oral },
  { name: 'Tetracycline Eye Ointment 1%', genericName: 'Tetracycline', category: 'ointment', dosageForm: 'Eye ointment', strength: '1%', unit: 'tubes', prescriptionRequired: true, unitCost: 4, sellingPrice: 8, currentStock: 90, reorderLevel: 25, maxStock: 250, shelfLocation: 'M1-02', description: 'Antibacterial eye ointment', storageConditions: topical },
  { name: 'Timolol Eye Drops 0.5%', genericName: 'Timolol', category: 'drops', dosageForm: 'Eye drops', strength: '0.5%', unit: 'bottles', prescriptionRequired: true, unitCost: 9, sellingPrice: 16, currentStock: 50, reorderLevel: 15, maxStock: 150, shelfLocation: 'M1-03', description: 'Antiglaucoma eye drops', storageConditions: oral },
  { name: 'Hydrocortisone 1% Cream', genericName: 'Hydrocortisone', category: 'cream', dosageForm: 'Cream', strength: '1%', unit: 'tubes', prescriptionRequired: true, unitCost: 4, sellingPrice: 8, currentStock: 100, reorderLevel: 25, maxStock: 300, shelfLocation: 'M2-01', description: 'Topical corticosteroid', storageConditions: topical },
  { name: 'Silver Sulfadiazine 1% Cream', genericName: 'Silver sulfadiazine', category: 'cream', dosageForm: 'Cream', strength: '1%', unit: 'tubes', prescriptionRequired: true, unitCost: 10, sellingPrice: 18, currentStock: 70, reorderLevel: 20, maxStock: 200, shelfLocation: 'M2-02', description: 'Topical antimicrobial burn cream', storageConditions: topical },
  { name: 'Povidone Iodine 10% Solution', genericName: 'Povidone iodine', category: 'solution', dosageForm: 'Topical solution', strength: '10%', unit: 'bottles', prescriptionRequired: false, unitCost: 8, sellingPrice: 15, currentStock: 120, reorderLevel: 30, maxStock: 300, shelfLocation: 'M2-03', description: 'Topical antiseptic', storageConditions: topical },
  { name: 'Chlorhexidine 0.05% Solution', genericName: 'Chlorhexidine', category: 'solution', dosageForm: 'Topical solution', strength: '0.05%', unit: 'bottles', prescriptionRequired: false, unitCost: 7, sellingPrice: 14, currentStock: 100, reorderLevel: 25, maxStock: 280, shelfLocation: 'M2-04', description: 'Topical antiseptic solution', storageConditions: topical },
];
